name: buildRoot
on:
    workflow_call:
jobs:
    buildRoot:
        name: Run buildRoot
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
            actions: read
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # - name: Setup pnpm environment
            #   uses: ./.github/actions/setup-pnpm

            - name: print input
              run: echo "buildRoot"

            - name: Setup environment
              uses: ./.github/actions/setup-azure
            #   with:
            #       azureCreds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Azure Login
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Verify Azure Login
              shell: bash
              run: az account show
