name: Build GitHub Runner Image

on:
    workflow_dispatch:
    push:
        branches:
            - workflow
        # paths:
        #     - "runner/**"

permissions:
    id-token: write
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        environment: Dev
        steps:
            - uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Login to ACR
              run: az acr login --name "${{ vars.TARGET_ENV_NAME }}acr"

            - name: Build and push image
              run: |
                  docker build -t "${{ vars.TARGET_ENV_NAME }}acr.azurecr.io/github-runner:latest" ./runner
                  docker push "${{ vars.TARGET_ENV_NAME }}acr.azurecr.io/github-runner:latest"

    start-aca-runner:
        runs-on: ubuntu-latest
        needs: build
        environment: Dev
        steps:
            - uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Start ACA Job
              run: |
                  az containerapp job start \
                      --name "${{ vars.TARGET_ENV_NAME }}-runner"  \
                      --resource-group "dev-${{ vars.TARGET_ENV_NAME }}" \

    test-runner:
        runs-on: [self-hosted, aca]
        needs: start-aca-runner
        environment: Dev
        steps:
            - uses: actions/checkout@v4

            - name: Show hostname & IP
              run: |
                  echo "Runner is:"
                  hostname
                  ip addr
