name: Codescan

on:
  push:
    branches: ["main"]

jobs:
  ESLint:
    name: Run ESLint code scans
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm environment
        uses: ./.github/actions/setup-pnpm

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npx eslint . --config eslint.config.js  --format @microsoft/eslint-formatter-sarif  --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload eslint results to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

      - name: Handle upload failure, print file content
        if: failure()
        run: cat eslint-results.sarif
        
  Snyk:
    name: Run Snyk code scans
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm environment
        uses: ./.github/actions/setup-pnpm

      - uses: snyk/actions/node@master
        with:
          args: test -d --sarif-file-output=snyk-results.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Upload Snyk results to GitHub
        id: uploadSnyk
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk-results.sarif
          wait-for-processing: true

      - name: Handle upload failure, print file content
        if: failure()
        run: cat snyk-results.sarif
