name: Eslint Scan

on:
  workflow_dispatch:

concurrency:
  group: codescan-group
  cancel-in-progress: true

jobs:
  ESLint:
    name: Run ESLint code scans
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm environment
        uses: ./.github/actions/setup-pnpm

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npx eslint . --config eslint.config.js --quiet --format @microsoft/eslint-formatter-sarif  --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload eslint results to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

      - name: Handle upload failure, print file content
        if: failure()
        run: cat eslint-results.sarif
